# -*- coding: utf-8 -*-
"""db &Tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_zsp-t-ezVmRFM-toIsWpiyUdjVerCq
"""

"""
Thin SQLite access layer for the IronBridge Procurement MCP server.

Every tool handler in server.py goes through here rather than writing
ad-hoc SQL inline. Business-rule validation lives in validation.py, not
here — this module only knows how to read/write rows.

Designed to import cleanly in any context: a plain script, a package
under mcp_server/, or pasted/exec'd in a Jupyter notebook — on any
Python 3.7+ interpreter.
"""

import hashlib
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Optional, List, Dict, Any


def _find_db_path() -> str:
    """
    Locate procurement.db without assuming a fixed folder depth or name.

    Priority:
      1. IRONBRIDGE_DB_PATH env var, if set — always wins.
      2. An existing db/procurement.db found by checking, in order:
         - next to this file            (this file's dir)/db/procurement.db
         - one level up from this file  (..)/db/procurement.db
         - the current working directory: cwd/db/procurement.db
         - one level up from cwd:       cwd/../db/procurement.db
      3. If none of those already exist, fall back to cwd/db/procurement.db
         so a fresh `build_db.py` run has a predictable place to create it.
    """
    env_path = os.environ.get("DB_PATH")
    if env_path:
        return env_path

    try:
        this_dir = Path(__file__).resolve().parent
    except NameError:
        this_dir = None  # __file__ not defined (REPL/notebook exec context)

    candidates = []
    if this_dir is not None:
        candidates.append(this_dir / "db" / "procurement.db")
        candidates.append(this_dir.parent / "db" / "procurement.db")
    cwd = Path.cwd()
    candidates.append(cwd / "db" / "procurement.db")
    candidates.append(cwd.parent / "db" / "procurement.db")

    for candidate in candidates:
        if candidate.exists():
            return str(candidate)

    # Nothing found yet — default to cwd/db/procurement.db so a fresh
    # `build_db.py` run has a predictable place to create it.
    return str(cwd / "db" / "procurement.db")


DB_PATH = _find_db_path()

# sqlite3.connect() will create the .db FILE if missing, but NOT missing
# parent directories — that's the other common cause of
# "unable to open database file". Make sure the folder exists.
Path(DB_PATH).resolve().parent.mkdir(parents=True, exist_ok=True)


@contextmanager
def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()


def hash_pin(pin: str) -> str:
    return hashlib.sha256(pin.encode()).hexdigest()


# --------------------------------------------------------------------------
# Read helpers
# --------------------------------------------------------------------------

def get_employee(employee_id: int) -> Optional[Dict[str, Any]]:
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM Employees WHERE EmployeeID = ?", (employee_id,)).fetchone()
        return dict(row) if row else None


def get_project(project_id: int) -> Optional[Dict[str, Any]]:
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM Projects WHERE ProjectID = ?", (project_id,)).fetchone()
        return dict(row) if row else None


def get_material(material_id: int) -> Optional[Dict[str, Any]]:
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM MaterialInventory WHERE MaterialID = ?", (material_id,)).fetchone()
        return dict(row) if row else None


def find_materials(category: Optional[str], name_contains: Optional[str]) -> List[Dict[str, Any]]:
    with get_conn() as conn:
        query = "SELECT * FROM MaterialInventory WHERE 1=1"
        params = []
        if category:
            query += " AND Category = ?"
            params.append(category)
        if name_contains:
            query += " AND MaterialName LIKE ?"
            params.append(f"%{name_contains}%")
        rows = conn.execute(query, params).fetchall()
        return [dict(r) for r in rows]


def get_purchase_request(request_id: int) -> Optional[Dict[str, Any]]:
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM PurchaseRequests WHERE RequestID = ?", (request_id,)).fetchone()
        return dict(row) if row else None


def equipment_status(equipment_type: Optional[str], site: Optional[str]) -> List[Dict[str, Any]]:
    with get_conn() as conn:
        query = "SELECT * FROM Equipment WHERE 1=1"
        params = []
        if equipment_type:
            query += " AND EquipmentType = ?"
            params.append(equipment_type)
        if site:
            query += " AND CurrentSite = ?"
            params.append(site)
        rows = conn.execute(query, params).fetchall()
        return [dict(r) for r in rows]


def project_requests_in_range(project_id: int, start_date: str, end_date: str) -> List[Dict[str, Any]]:
    with get_conn() as conn:
        rows = conn.execute(
            """
            SELECT pr.*, m.MaterialName, e.Name AS RequestedBy
            FROM PurchaseRequests pr
            JOIN MaterialInventory m ON m.MaterialID = pr.MaterialID
            JOIN Employees e ON e.EmployeeID = pr.EmployeeID
            WHERE pr.ProjectID = ? AND date(pr.RequestDate) BETWEEN date(?) AND date(?)
            ORDER BY pr.RequestDate
            """,
            (project_id, start_date, end_date),
        ).fetchall()
        return [dict(r) for r in rows]


# --------------------------------------------------------------------------
# Write helpers (called only after handler-level authorization + validation)
# --------------------------------------------------------------------------

def create_purchase_request(project_id, employee_id, material_id, quantity):
    with get_conn() as conn:
        material = conn.execute(
            "SELECT UnitPrice FROM MaterialInventory WHERE MaterialID = ?", (material_id,)
        ).fetchone()
        if material is None:
            raise ValueError(f"Unknown MaterialID {material_id}")
        estimated_cost = material["UnitPrice"] * quantity
        cur = conn.execute(
            """
            INSERT INTO PurchaseRequests
                (ProjectID, EmployeeID, MaterialID, Quantity, EstimatedCost, ApprovalLevel, Status)
            VALUES (?, ?, ?, ?, ?, 1, 'Pending')
            """,
            (project_id, employee_id, material_id, quantity, estimated_cost),
        )
        request_id = cur.lastrowid
        log_action(conn, employee_id, "create_purchase_request", request_id, f"qty={quantity}, est_cost={estimated_cost}")
        return request_id, estimated_cost


def approve_purchase_request(request_id: int, approver_id: int):
    with get_conn() as conn:
        conn.execute("UPDATE PurchaseRequests SET Status = 'Approved' WHERE RequestID = ?", (request_id,))
        log_action(conn, approver_id, "approve_purchase_request", request_id, "approved")


def escalate_purchase_request(request_id: int, reason: str, actor_id: int):
    with get_conn() as conn:
        conn.execute(
            "UPDATE PurchaseRequests SET Status = 'Escalated', ApprovalLevel = ApprovalLevel + 1 WHERE RequestID = ?",
            (request_id,),
        )
        log_action(conn, actor_id, "escalate_purchase_request", request_id, reason)


def reserve_material(request_id: int, material_id: int, quantity: float, actor_id: int):
    with get_conn() as conn:
        conn.execute(
            "UPDATE MaterialInventory SET QuantityAvailable = QuantityAvailable - ?, LastUpdated = datetime('now') WHERE MaterialID = ?",
            (quantity, material_id),
        )
        conn.execute("UPDATE PurchaseRequests SET Status = 'Reserved' WHERE RequestID = ?", (request_id,))
        log_action(conn, actor_id, "reserve_material", request_id, f"qty={quantity}")


def log_action(conn, actor_id, action, target_id, detail):
    conn.execute(
        "INSERT INTO AuditLog (ActorID, Action, TargetID, Detail) VALUES (?, ?, ?, ?)",
        (actor_id, action, target_id, detail),
    )