# -*- coding: utf-8 -*-
"""http_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TnOpJL_WlH7BDnNtO8L9kzVCQ2yk-FQN
"""

import os

from mcp.server.lowlevel import Server
from mcp.server.models import InitializationOptions
from mcp.server.streamable_http_manager import StreamableHTTPSessionManager
from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import PlainTextResponse
from starlette.routing import Mount, Route


def build_asgi_app(server: Server, init_options: InitializationOptions):
    session_manager = StreamableHTTPSessionManager(app=server, stateless=False)

    async def handle_mcp(scope, receive, send):
        request = Request(scope, receive=receive)
        expected = os.environ.get("IRONBRIDGE_API_TOKEN")
        if expected:
            got = request.headers.get("authorization", "")
            if got != f"Bearer {expected}":
                response = PlainTextResponse("Unauthorized", status_code=401)
                await response(scope, receive, send)
                return
        await session_manager.handle_request(scope, receive, send)

    async def health(request: Request):
        return PlainTextResponse("ok")

    app = Starlette(
        routes=[
            Route("/health", health, methods=["GET"]),
            # `handle_mcp` is a raw ASGI callable (scope, receive, send) --
            # it needs Mount, not Route. Route wraps its endpoint expecting
            # a Starlette-style `async def handler(request) -> Response`
            # and calls it as `await handler(request)`, which raises
            # "missing 2 required positional arguments: 'receive' and
            # 'send'" for a raw ASGI function. Mount passes scope/receive/
            # send straight through, unmodified. This is also exactly the
            # pattern the mcp SDK's own FastMCP.streamable_http_app() uses
            # internally for its equivalent handler.
            Mount("/mcp", app=handle_mcp),
        ],
        lifespan=lambda app: session_manager.run(),
    )
    return app